language: python
python:
  # as we support centos, which only has 2.6, we use this.
  # in theory, there is no issue with 2.7 at all
  - "2.6"

install:
  - git submodule update --init --recursive
  # at this point, we are in our devel repo : travis/repo
  - git clone --recurse-submodules https://github.com/Byron/bdep-oss.git ../bdep-oss
  # fix up the image to be good for us
  - sudo ln -s `which python` /usr/bin/python2.6

script:
  - cd bin/posix
  # we just check if we can execute progams, not if the unit-tests of them work
  # the latter are handled individually
  - ./nosetests
  - ./pgit submodule query
  - cd ../..
  - bash --verbose lib/components/core/.travis-script.sh