logging:
  level: INFO
  disable: 0

assembly:
  trees:
    # root of the main application
    core: '{process.executable.dirname}/../..'
    # side-by-side assembly with dependencies that are open source software
    oss-dependencies: '{assembly.trees.core}/../bdep-oss'
    # side-by-side assembly containing dependencies with proprietary licenses
    nonfree-dependencies: '{assembly.trees.core}/../bdep-nonfree'

package-manager:
  include:
   # pull in the entire software configuration
   - '{assembly.trees.nonfree-dependencies}/etc'
   - '{assembly.trees.oss-dependencies}/etc'
  environment:
    variables:
      regex:
        is_path:            '^(.*path|.+paths|.+tree|.+location|.+home|ocio)$'
        path_is_appendable: '^(?!(ocio|rmantree)).*$'

packages:
  python:
    version: '2.7'
